# Shell to use with Make
SHELL := /bin/bash

### Colocar os valores de cada arquivo na coluna de uma matriz
### Discplina RII - Aluno: Wesley Pereira da Silva

# Set important Paths
#PROJECT := 'Semana 4 - RI'
LOCALPATH := $(CURDIR)/$(PROJECT)
PYTHONPATH := $(LOCALPATH)/


help:
	@echo "    executa"
	@echo "    Processa o arquivo arquivosaida no diretorio corrente."
	
all: 	executa


compila:	
	python t1-main.py
	

executa:
	python t1-main.py
	


clear:
	rm -Rf arquivosaida