# Shell to use with Make
SHELL := /bin/bash

###
### Discplina RII - Aluno: Wesley Pereira da Silva

# Set important Paths
#PROJECT :21'
LOCALPATH := $(CURDIR)/$(PROJECT)
PYTHONPATH := $(LOCALPATH)/


help:
	@echo "    executa"
	@echo "    Processa o arquivo arquivosaida no diretorio corrente."

all: 	executa


compila: 	executa



executa:
	python T25.py


#clear:
#	rm  relatorio.pdf resposta.txt
