# Shell to use with Make
SHELL := /bin/bash

### Indexa as respostas de verificacao de links
### Discplina RII - Aluno: Wesley Pereira da Silva

# Set important Paths
#PROJECT := 'Semana 4 - RI'
LOCALPATH := $(CURDIR)/$(PROJECT)
PYTHONPATH := $(LOCALPATH)/


help:
	@echo "    executa"
	@echo "    Processa o arquivo arquivosaida no diretorio corrente."
	
all: 	executa


compila:	
	./Processa_pRiUfes.sh
	

executa:
	./Processa_pRiUfes.sh
	


clear:
	rm -Rf observacoes.txt erros.txt